#!/usr/bin/env bash

function disable_ipv6 {
  echo 'net.ipv6.conf.all.disable_ipv6=1' > /etc/sysctl.d/40-ipv6_disable.conf
  echo 'net.ipv6.conf.default.disable_ipv6=1' >> /etc/sysctl.d/40-ipv6_disable.conf
  echo 'net.ipv6.conf.lo.disable_ipv6=1' >> /etc/sysctl.d/40-ipv6_disable.conf
  sysctl --system
}

disable_ipv6
